apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-generator
  template:
    metadata:
      labels:
        app: playlist-generator
    spec:
      containers:
      - name: playlist-generator
        image: personal-playlist-generator
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
